# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippetitem',
            old_name='snippet_id',
            new_name='video_id',
        ),
    ]
